on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Bucket on OBS
        uses: huaweicloud/obs-helper@v1.2.0
        id: delete_bucket_on_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          operationType: deletebucket
          bucket_name: bucket-test
          clear_bucket: false