on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Folder To OBS
        uses: huaweicloud/obs-helper@v1.1.0
        id: upload_folder_to_obs
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: ${region}
          bucket_name: ${bucket_name}
          local_file_path: resource/upload/folder2
          obs_file_path: src/upload/newFolder
          operation_type: upload
          include_self_folder: true